# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e51a6681dddd4be3da409e904334a6327886eb22ef22927a81e847e1069c173508b65af887af3dd121ecfe236d7f386be5056ef8d82094c818bef1e99599048

test:
  secret_key_base: 580b96e1e2db2ec759a48eeca05fbcaed9b5f95687c4cea3f9fbcdc8681dc6d29a0343b3f770e8dfab0c02043e6c8ef9446b377e598258d05b83330548651dab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
